version: '2'
services:
  hub:
    image: selenium/hub:latest
    restart: always
    ports:
      - "0.0.0.0:4445:4444"

  chrome:
    image: selenium/node-chrome:latest
    restart: always
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  firefox:
    image: selenium/node-firefox:latest
    restart: always
    depends_on:
      - hub
    environment:
      HUB_HOST: hub