version: '2'
services:
  firefox:
    image: selenium/node-firefox:latest
    restart: always
    environment:
      - HUB_HOST=10.10.2.22
      - HUB_PORT=4446
      - REMOTE_HOST=http://10.10.2.22:8855
    ports:
      - 0.0.0.0:8855:5555