version: '3'
services:
  mongodb:
    image: mongo:4.2.2
    container_name: mongodb
    restart: always
    volumes:
      - 'C:/dkvl/MongoDB/data/db:/data/db'
      - 'C:/dkvl/MongoDB/data/backup:/data/backup'
      - 'C:/dkvl/MongoDB/data/configdb:/data/configdb'
    ports:
      - 0.0.0.0:27017:27017
