version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
#    volumes:
#      - /data/db:/data/db
#      - /data/backup:/data/backup
#      - /data/configdb:/data/configdb
    ports:
      - 27017:27017

