version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ~/dkvl/mongodb/data/db:/data/db
      - ~/dkvl/mongodb/data/backup:/data/backup
      - ~/dkvl/mongodb/data/configdb:/data/configdb
    ports:
      - 27017:27017

