version: '3'
services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    volumes:
      - ~/dkvl/mysql/mydir:/mydir
      - ~/dkvl/mysql/datadir:/var/lib/mysql
      - ~/dkvl/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ~/dkvl/mysql/docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
      - "MYSQL_DATABASE=mydb"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
